[global]
disableWatchdogWarning = true

[server]
headless = true

[client]
showErrorDetails = true

[runner]
fastReruns = true

[theme]
base="dark"
primaryColor="#00ff88"
backgroundColor="#000000"
secondaryBackgroundColor="#111111"
textColor="#ffffff"

[package]
installer = "pip"
